
/* https://projecteuler.net/problem=2


Even Fibonacci numbers
Problem 2


Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

#include <stdio.h>

int fibonacci (int l){  // (int l) it's the limit, in this case four million (4000000)

	int s=0;            // (int s) it's the sum
	int a, b, c;
	a=1;                // (int a) it's the first term
	b=1;                // (int b) it's the second term
	c=0;                // (int c) it will work kind of like an temporary integer

	while(c<l){         // While c it's less then l
		if(c%2 == 0){   // If c it's a pair number,
			s=s+c;      // the sum s equals s plus c
		}
		c=a+b;          // Then c equals a plus b
		a=b;            // a equals b
		b=c;            // b equals c.
	}
	return s;           // Return (int s), the sum of the pairs in the Fibonacci sequence   
}

void main () {

int i;

	printf("Define a limit: ");
	scanf("%d",&i);

	printf("\nThe sum of the pairs in the Fibonacci sequence it's: %d\n", fibonacci(i));
}